services:
  - type: web
    name: veria-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: source /opt/render/project/venv/bin/activate && gunicorn server:app
    plan: free